- name: installing nginx
  hosts: nginx
  become: yes
  vars:
   
  tasks:
  - name: printing
    ansible.builtin.debug:
      msg: " {{ "http://user:password@www.acme.com:9000/dir/index.html?query=term#fragment" | urlsplit('hostname') }} "
      