- name: installing nginx
  hosts: nginx
  become: yes
  vars:
    name: "http://user:password@web.rakeshreddy.online:9000/dir/index.html?query=term#fragment"
  tasks:
  - name: printing
    ansible.builtin.debug:
      msg: "{{ name | urlsplit('hostname') }}"
      